import { collection, getDocs } from "firebase/firestore"
import Head from "next/head"
import { useMemo, useState } from "react"
import Card from "../components/Card"
import Form from "../components/Form"
import { db } from "../lib/firebase"

export default function Home() {
  const [blogs, setBlogs] = useState([])

  useMemo(() => {
    const getBlog = async () => {
      const querySnapshot = await getDocs(collection(db, "blogs"))
      querySnapshot.forEach((doc) => {
        setBlogs((values) => [{ id: doc.id, ...doc.data() }, ...values])
      })
    }
    getBlog()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Form setBlog={setBlogs} />

      {blogs.map((blog) => (
        <Card blog={blog} key={blog.id} />
      ))}
    </>
  )
}
